In [ ]:
! pip3 install numpy 


Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.


In [2]:
import numpy as np

*Q1. Building the class register*

Three students' marks arrived as three separate lists, and one old record arrived as text.

Tasks

1.Build one table from s1, s2 and s3.

2.From that table, print the number of students and the number of subjects as two separate numbers.

3.Print the total count of marks entries stored in the table.

4.Store the same table as decimals instead of whole numbers.

5.Convert old into a form where arithmetic works, then print the total marks of both students.

6.Attach old below the main table so that all five students sit in one table.


Expected output — task 5

[268 246]


Expected output — task 6

[[ 72  85  60  91]

 [ 45  30  98  55]

 [ 88  66  74 100]

 [ 62  71  55  80]
 
 [ 49  58  66  73]]
 

In [ ]:

#QUESTION_1

s1 = [72, 85, 60, 91]
s2 = [45, 30, 98, 55]
s3 = [88, 66, 74, 100]
old = np.array([['62', '71', '55', '80'],
                ['49', '58', '66', '73']])

#1.
arr = np.array([s1, s2, s3])
print("Original array:\n", arr)

#2.
# students= np.where(arr[0:, :1])[0]
print("No of Students:\n", arr.shape[0])

# subject = np.where(arr[:, :4])[0]
print("No of Subjects:\n", arr.shape[1])


#3
print("total elements:\n",np.size(arr))

#4
print("decimal values:\n",arr.astype(float))

#5
old = old.astype('int32')
print("Sum of old array along axis 1:\n", np.sum(old, axis=1)) 

#6
print(arr.astype(float)) #6
print("Vertical Stack of both arrays:\n", np.vstack((arr,old))) #7

Original array:
 [[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]]
No of Students:
 3
No of Subjects:
 4
total elements:
 12
decimal values:
 [[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]]
Sum of old array along axis 1:
 [268 246]
[[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]]
Vertical Stack of both arrays:
 [[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]
 [ 62  71  55  80]
 [ 49  58  66  73]]



*Q2. Templates and sequences*
Tasks

1.Create a blank mark sheet for 6 students and 4 subjects, every entry starting at 0.

2.Create a table of the same size where every student is temporarily given 35.

3.A batch has roll numbers running from 101 to 130. Generate only the alternate roll numbers, and print how many were generated.

4.Split a 3-hour practical into 7 equally spaced time markers, including both the start and the end.

5.Create a 5 × 5 table that has 10 on the diagonal and 0 everywhere else.

6.Create a 4 × 4 table that has 100 on the diagonal and 35 everywhere else.

Expected output — task 3

[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
15


Expected output — task 4

[0.  0.5 1.  1.5 2.  2.5 3. ]


Expected output — task 6

[[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]

In [ ]:
#QUESTION_2

#1
table = np.zeros((6,4))
print("Table:\n", table)

#2
table2 = np.full((6,4), 35)
print("Table2:\n", table2)

#3
roll_No = np.arange(101, 131, 2)
print("Roll Numbers:\n", roll_No)

#4
print("7 equally spaced time markers:\n",np.linspace(0,3,7))

#5
arr = np.eye(5, dtype=int) * 10
print("diagonal array:\n", arr)

#6
arr1 = np.full((4,4), 35, dtype=int) + np.eye(4, dtype=int) * 65
print("Array1:\n", arr1)

Table:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Table2:
 [[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]
Roll Numbers:
 [101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
7 equally spaced time markers:
 [0.  0.5 1.  1.5 2.  2.5 3. ]
diagonal array:
 [[10  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 10]]
Array1:
 [[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]



*Q3. The attendance row*
Tasks

1.Print the first and the last student's attendance without writing the class strength anywhere in your code.

2.Print the attendance of every alternate student, starting from the second one.

3.Print the last four values.

4.Reverse the row, then print every third value of the reversed row.

5.Change the attendance of the two middle students to 30 each.

6.Compare the first half of the row with the second half position by position, and print the difference.

7.Print the top three values of the row after reversing it.


Expected output — task 4

[23  9 12 22]


Expected output — task 6

[-2  9  4 -5 -3]

In [ ]:

#QUESTION_3

present = np.array([22, 18, 25, 12, 20, 24, 9, 21, 17, 23])

#1
print(present[0], present[-1])

#2
alt_attendance = present[::2]
print("alt attendance: \n", alt_attendance)

#3
print("last 4 values: \n", present[:-5:-1])

#4
rev = present[::-1]
print("reversed 3rd value: \n", rev[::3])

#5
middle_std = len(present) // 2
present[middle_std-1 : middle_std+1] = [30, 30]
print("updated: \n", present)

#6
first = present[:len(present)//2]
second = present[len(present)//2:]
difference = first - second
print("diffrence: \n",difference)

#7
print("top 3 value: \n", rev[:3:])


22 23
alt attendance: 
 [22 25 20  9 17]
last 4 values: 
 [23 17 21  9]
reversed 3rd value: 
 [23  9 12 22]
updated: 
 [22 18 25 12 30 30  9 21 17 23]
diffrence: 
 [-8  9  4 -5  7]
top 3 value: 
 [23 17 21]


*Q4. Reading the mark sheet*

The columns are Math, Physics, Chemistry and English.

Tasks

1.Print the Physics and Chemistry marks of the middle three students only.

2.Print the last subject's marks for the whole class.

3.Produce a table containing only the first and the last subject of every student.

4.Print the mark sheet with the students in reverse order.

5.Increase only the Chemistry marks of the whole class by 5, leaving the rest unchanged.

6.Print the mark that sits in the last row and the second-last column.

7.Produce a table of the last two students and their first two subjects.


Expected output — task 1

[[30 98]

 [66 74]

 [92 55]]


Expected output — task 3

[[ 72  91]

 [ 45  55]

 [ 88 100]

 [ 95  40]

 [ 30  70]]

In [ ]:

#QUESTION_4

marks = np.array([[72, 85, 60, 91],
                  [45, 30, 98, 55],
                  [88, 66, 74, 100],
                  [95, 92, 55, 40],
                  [30, 48, 62, 70]])


#1
print ("Phy and chem marks of middle 3: \n",marks[1:4,1:3])

#2
print("Last sub marks: \n", marks[:,3:4])

#3
print("table of 1st nd nth sub: \n", marks[:,[0,-1]])

#4
print("marks in reverse order: \n", marks[::-1, :])

#5
print("incresed marks: \n", marks[:,2:3]+5)

#6
print("marks of last row 2nd last col: \n",marks[-1, -2])

#7



Phy and chem marks of middle 3: 
 [[30 98]
 [66 74]
 [92 55]]
Last sub marks: 
 [[ 91]
 [ 55]
 [100]
 [ 40]
 [ 70]]
table of 1st nd nth sub: 
 [[ 72  91]
 [ 45  55]
 [ 88 100]
 [ 95  40]
 [ 30  70]]
marks in reverse order: 
 [[ 30  48  62  70]
 [ 95  92  55  40]
 [ 88  66  74 100]
 [ 45  30  98  55]
 [ 72  85  60  91]]
incresed marks: 
 [[ 65]
 [103]
 [ 79]
 [ 60]
 [ 67]]
marks of last row 2nd last col: 
 62



Q5. Scholarship shortlisting

Tasks

1.Print the totals of students who scored above 250.

2.Print the totals of students scoring above 180 but below 250.

3.Print the totals of students who scored either below 150 or above 380.

4.Print how many students fall in the band of task 2.

5.Print the average of only those students who scored above 200.

6.Print the index position of every student below 150.

7.Print the highest total among the students who did not make the merit band of task 1.


Expected output — task 2

[245 199]

2


Expected output — task 6

[4 9]

In [ ]:
#QUESTION_5

totals = np.array([245, 310, 178, 392, 140, 265, 199, 155, 288, 132])


#1
n = np.arange()