In [2]:

import numpy as np


In [3]:
#1

marks = np.array([[88, 96, 95],
                  [72, 99, 91],
                  [98, 85, 97],
                  [60, 75, 80]])

bonus = np.array([5, 2, 8])

marks_bonus = marks + bonus

capped = np.minimum(marks_bonus, 100)

count_capped = np.sum(marks_bonus > 100)

print(capped)
print("Marks capped:", count_capped)

[[ 93  98 100]
 [ 77 100  99]
 [100  87 100]
 [ 65  77  88]]
Marks capped: 4


In [4]:
#2
arr = np.ones((5, 5), dtype=int)

arr[1:-1, 1:-1] = 0

print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [5]:
#3


arr = np.arange(30).reshape(5, -1).T

print(arr)
print(arr.shape)


[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]
(6, 5)


In [6]:
#4
heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])

first = np.hstack((heights, weights)) #→ joins horizontally.

print(first)
print(first.shape)



table = np.column_stack((heights, weights)) #→ creates columns.

print(table)
print(table.shape)

[172 158 181 166  68  52  84  59]
(8,)
[[172  68]
 [158  52]
 [181  84]
 [166  59]]
(4, 2)


In [7]:
#5
sales = np.array([120, 135, 98, 160, 175, 190,
                  88, 92, 105, 210, 198, 230])

quarters = sales.reshape(4, 3)

averages = quarters.mean(axis=1)

best_quarter = np.argmax(averages)

print(quarters)
print("Quarter averages:", averages)
print("Highest average quarter:", best_quarter)
print("Highest average:", averages[best_quarter])

[[120 135  98]
 [160 175 190]
 [ 88  92 105]
 [210 198 230]]
Quarter averages: [117.66666667 175.          95.         212.66666667]
Highest average quarter: 3
Highest average: 212.66666666666666


In [8]:
#6
a = np.array([2, 3, 4])

table = a.reshape(-1, 1) * a

print(table)

[[ 4  6  8]
 [ 6  9 12]
 [ 8 12 16]]


In [9]:
#7
arr = np.arange(1, 21)

arr[arr % 3 == 0] = -1

print(arr)

[ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1 16 17 -1 19 20]


In [10]:
#8
X = np.array([[50, 1200, 3],
              [80, 1500, 9],
              [65, 900, 5],
              [95, 2000, 7]])

col_min = X.min(axis=0)
col_max = X.max(axis=0)

normalized = (X - col_min) / (col_max - col_min)

print(normalized)
print("Column minimums:", normalized.min(axis=0))
print("Column maximums:", normalized.max(axis=0))

[[0.         0.27272727 0.        ]
 [0.66666667 0.54545455 1.        ]
 [0.33333333 0.         0.33333333]
 [1.         1.         0.66666667]]
Column minimums: [0. 0. 0.]
Column maximums: [1. 1. 1.]


In [11]:
#9
scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])

medals = np.where(
    scores >= 90, "Gold",
    np.where(
        scores >= 75, "Silver",
        np.where(scores >= 60, "Bronze", "None")
    )
)

print(medals)

print("Gold:", np.sum(medals == "Gold"))
print("Silver:", np.sum(medals == "Silver"))
print("Bronze:", np.sum(medals == "Bronze"))
print("None:", np.sum(medals == "None"))

['Gold' 'Bronze' 'Silver' 'None' 'Gold' 'Silver' 'None' 'Bronze']
Gold: 2
Silver: 2
Bronze: 2
None: 2


In [12]:
#10
m = np.array([[10, 80, 45],
              [55, 20, 99],
              [70, 33, 12]])

rows, cols = np.where(m > 50)

print("Rows:", rows)
print("Columns:", cols)

print("Elements:", m[m > 50])

new_m = m.copy()
new_m[m > 50] = 0

print(new_m)


print(m)

Rows: [0 1 1 2]
Columns: [1 0 2 0]
Elements: [80 55 99 70]
[[10  0 45]
 [ 0 20  0]
 [ 0 33 12]]
[[10 80 45]
 [55 20 99]
 [70 33 12]]


In [13]:
#11
s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])

rows = np.vstack((s1, s2, s3))
columns = np.column_stack((s1, s2, s3))

print(rows)
print(rows.shape)

print(columns)
print(columns.shape)

print(np.array_equal(rows.T, columns))


[[12 15 11 19 14]
 [22 18 25 21 20]
 [31 35 29 33 30]]
(3, 5)
[[12 22 31]
 [15 18 35]
 [11 25 29]
 [19 21 33]
 [14 20 30]]
(5, 3)
True


In [14]:
#12
np.random.seed(1)

arr = np.random.randint(1, 101, (6, 6))

row_max = arr.max(axis=1)
col_min = arr.min(axis=0)

print(arr)
print("Row-wise maximum:", row_max)
print("Column-wise minimum:", col_min)


[[38 13 73 10 76  6]
 [80 65 17  2 77 72]
 [ 7 26 51 21 19 85]
 [12 29 30 15 51 69]
 [88 88 95 97 87 14]
 [10  8 64 62 23 58]]
Row-wise maximum: [76 80 85 69 97 64]
Column-wise minimum: [ 7  8 17  2 19  6]


In [15]:
#13
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [1, 0, 2]])

result1 = A @ B.T
result2 = A.T @ B

print(result1)
print(result1.shape)

print(result2)
print(result2.shape)

# A @ B is invalid because:
# A has shape (2,3) and B has shape (2,3).
# For matrix multiplication, inner dimensions must match.

[[ 50   7]
 [122  16]]
(2, 2)
[[11  8 17]
 [19 16 28]
 [27 24 39]]
(3, 3)


In [16]:
#14
hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])

# Convert into column vectors
hours_col = hours.reshape(-1, 1)
attendance_col = attendance.reshape(-1, 1)

print("hours_col:")
print(hours_col)
print("Shape:", hours_col.shape)

print("attendance_col:")
print(attendance_col)
print("Shape:", attendance_col.shape)


# Join into two-column table
table = np.hstack((hours_col, attendance_col))

print("Table:")
print(table)
print("Shape:", table.shape)


# Calculate total for each row
total = table.sum(axis=1).reshape(-1, 1)

print("Total:")
print(total)
print("Shape:", total.shape)


# Attach total as third column
three_column = np.hstack((table, total))

print("Three-column table:")
print(three_column)
print("Shape:", three_column.shape)


# Weighted score
w = np.array([0.5, 0.2, 0.3])

scores = three_column @ w

print("Scores:")
print(scores)
print("Shape:", scores.shape)


# Average
average = scores.mean()

print("Average:", average)


# Above average = 1, otherwise 0
result = np.where(scores > average, 1, 0)

print("Final result:", result)
print("Shape:", result.shape)

hours_col:
[[ 2]
 [ 8]
 [ 5]
 [10]
 [ 3]
 [ 7]]
Shape: (6, 1)
attendance_col:
[[55]
 [92]
 [70]
 [98]
 [60]
 [85]]
Shape: (6, 1)
Table:
[[ 2 55]
 [ 8 92]
 [ 5 70]
 [10 98]
 [ 3 60]
 [ 7 85]]
Shape: (6, 2)
Total:
[[ 57]
 [100]
 [ 75]
 [108]
 [ 63]
 [ 92]]
Shape: (6, 1)
Three-column table:
[[  2  55  57]
 [  8  92 100]
 [  5  70  75]
 [ 10  98 108]
 [  3  60  63]
 [  7  85  92]]
Shape: (6, 3)
Scores:
[29.1 52.4 39.  57.  32.4 48.1]
Shape: (6,)
Average: 43.0
Final result: [0 1 0 1 0 1]
Shape: (6,)


In [17]:
#15
arr = np.array([10, 20, 30, 40, 50])

normalized = (arr - arr.min()) / (arr.max() - arr.min())

print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [18]:
#16 flatten() v/s ravel()
m = np.array([[4, 8, 15],
              [16, 23, 42]])

flat = m.flatten()
rav = m.ravel()

flat[0] = 999
rav[0] = 888

print("Flatten:", flat)
print("Ravel:", rav)

print("Original matrix:")
print(m)

# flatten() creates a copy, so changing flat does not affect m.
# ravel() usually returns a view, so changing rav changes m.

Flatten: [999   8  15  16  23  42]
Ravel: [888   8  15  16  23  42]
Original matrix:
[[888   8  15]
 [ 16  23  42]]


In [19]:
#17 Temperature anayalsis
np.random.seed(7)

temps = np.random.randint(15, 41, 28)

weeks = temps.reshape(4, 7)

weekly_average = weeks.mean(axis=1)

hottest_week = np.argmax(weekly_average)

days_above_35 = np.sum(temps > 35)

print("Weeks:")
print(weeks)

print("Weekly averages:")
print(weekly_average)

print("Hottest week index:", hottest_week)
print("Days above 35:", days_above_35)

Weeks:
[[30 19 40 37 18 34 38]
 [22 40 29 38 23 40 29]
 [25 23 22 21 19 31 22]
 [27 15 26 38 21 34 27]]
Weekly averages:
[30.85714286 31.57142857 23.28571429 26.85714286]
Hottest week index: 1
Days above 35: 7


In [20]:
#18. Is matrix multiplication commutative?
np.random.seed(10)

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

AB = A @ B
BA = B @ A

print("A:")
print(A)

print("B:")
print(B)

print("A @ B:")
print(AB)

print("B @ A:")
print(BA)

print("Are they equal?", np.array_equal(AB, BA))

# Matrix multiplication is generally NOT commutative.
# Therefore, A @ B is generally different from B @ A.

A:
[[5 1 2]
 [1 2 9]
 [1 9 7]]
B:
[[5 4 1]
 [5 7 9]
 [2 9 5]]
A @ B:
[[ 34  45  24]
 [ 33  99  64]
 [ 64 130 117]]
B @ A:
[[ 30  22  53]
 [ 41 100 136]
 [ 24  65 120]]
Are they equal? False


In [21]:
#19 Replace marks below 35

marks = np.array([[45, 28, 67, 80],
                  [33, 90, 55, 41],
                  [72, 66, 30, 58],
                  [88, 79, 91, 84],
                  [25, 40, 38, 52]])

marks[marks < 35] = 35

totals = marks.sum(axis=1)

topper = np.argmax(totals)

print(marks)
print("Student totals:", totals)
print("Topper index:", topper)
print("Topper total:", totals[topper])

[[45 35 67 80]
 [35 90 55 41]
 [72 66 35 58]
 [88 79 91 84]
 [35 40 38 52]]
Student totals: [227 221 231 342 165]
Topper index: 3
Topper total: 342


In [22]:
#20 Slice v/s Copy
arr = np.arange(1, 11)

view = arr[2:6]
copy = arr[2:6].copy()

view[0] = 999
copy[0] = 999

print("Original:", arr)
print("View:", view)
print("Copy:", copy)

Original: [  1   2 999   4   5   6   7   8   9  10]
View: [999   4   5   6]
Copy: [999   4   5   6]


In [ ]:
#21 np.diag
m = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

diagonal = np.diag(m)

print(diagonal)

arr = np.array([10, 20, 30, 40])
diagonal_matrix = np.diag(arr)

print(diagonal_matrix)

[ 1  6 11 16]
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]
