In [ ]:
! pip3 install numpy

In [1]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [7]:
# 1. Create a 1D array of integers from 1 to 10.
a = np.arange(1,11)
print("list:", a)


# 2. Creata a 3X3 martix of all zeros, and another of all ones.
mat_1 = np.zeros((3,3))
mat_2 = np.ones((3,3))
print("Matrix of zeros:")
print(mat_1)
print("Matrix of ones:")
print(mat_2)

# 3.Create an array of all even number b/w 2 and 20(inclusive) using np.arange().
nums = np.arange(2,21,2)
print("Even numbers:", nums)

# 4.Crete an array of 5 part from 0 to 1 using np.linspace().
arr = np.linspace(0,1,5)
print("Linspace array:", arr)

list: [ 1  2  3  4  5  6  7  8  9 10]
Matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matrix of ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Even numbers: [ 2  4  6  8 10 12 14 16 18 20]
Linspace array: [0.   0.25 0.5  0.75 1.  ]


In [35]:
mat = np.arange(5*4).reshape(5,4)
print("matrix:")
print(mat)

print("Rows:")
print(mat[::4,::3])



matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Rows:
[[ 0  3]
 [16 19]]


In [3]:
rolls = np.random.randint(1, 7, 10)

print(rolls)


[4 5 3 5 5 2 3 3 3 5]


In [4]:
rolls = np.random.randint(35,101,20)
print(np.mean(rolls))
print(np.median(rolls))
print(np.std(rolls))



69.95
69.5
20.941525732381585


In [6]:
# min, max, sum, mean, median, std, var
arr = np.arange(6).reshape(2,3)
print(arr)
print("min", np.min(arr))
print("row min", arr.min(axis=1))
print("col min", arr.min(axis=0))

print("sum of the array:", np.sum(arr))
print("sum of the rows:", arr.sum(axis=1))
print("sum of the columns:", arr.sum(axis=0))

print("meadian", np.median(arr))
print("std", np.std(arr))

[[0 1 2]
 [3 4 5]]
min 0
row min [0 3]
col min [0 1 2]
sum of the array: 15
sum of the rows: [ 3 12]
sum of the columns: [3 5 7]
meadian 2.5
std 1.707825127659933
