# NumPy Practice Session

Quick one-line recaps only — the focus here is practice. For each topic, solve the questions in the empty code cells provided.


## 1. Array Creation Basics

_`np.array(list)` → from list | `np.zeros(shape)` → all 0s | `np.ones(shape)` → all 1s | `np.full(shape, val)` → custom value | `np.arange(start,stop,step)` → like range()_


**Q1.1** Create a 1D array of 6 numbers of your choice.

In [43]:
# Write your code here
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr)


[10 20 30 40 50 60]


**Q1.2** Create a 3x3 array of zeros and a 2x2 array filled with the value 7.

In [44]:
# Write your code here
zeros = np.zeros((3, 3))
sevens = np.full((2, 2), 7)

print(zeros)
print(sevens)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7]
 [7 7]]


**Q1.3** Create an array of odd numbers from 1 to 21 using `arange`.

In [45]:
# Write your code here
arr = np.arange(1, 22, 2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21]


## 2. Advanced Creation

_`.reshape(r,c)` → change shape | `np.linspace(start,stop,num)` → num evenly spaced values | `np.eye(n)` → n×n identity matrix_


**Q2.1** Create numbers 0 to 11 using `arange` and reshape into a 3x4 matrix.

In [46]:
# Write your code here
arr = np.arange(12).reshape(3, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Q2.2** Generate 7 evenly spaced values between 10 and 50 using `linspace`.

In [47]:
# Write your code here
arr = np.linspace(10, 50, 7)
print(arr)

[10.         16.66666667 23.33333333 30.         36.66666667 43.33333333
 50.        ]


**Q2.3** Create a 5x5 identity matrix.

In [48]:
# Write your code here
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 3. Array Attributes

_`.shape` → dimensions tuple | `.ndim` → no. of dimensions | `.size` → total elements | `.dtype` → data type_


**Q3.1** Create a (4,3) array and print its shape, ndim, size, and dtype.

In [49]:
# Write your code here


**Q3.2** Create a (3,) vector and check if it's compatible for a dot product with a (5,3) matrix.

In [50]:
# Write your code here


## 4. Indexing & Slicing

_`arr[i]` / `arr[r,c]` → access | `arr[a:b, c:d]` → sub-matrix | `arr[::step]` → step slicing | `arr[::-1]` → reverse_


**Q4.1** Create a 4x4 array with values 1-16. Extract row 2, column 3.

In [51]:
# Write your code here


**Q4.2** From the same array, extract the sub-matrix of the first two rows and last two columns.

In [52]:
# Write your code here


**Q4.3** Reverse the array row-wise, then column-wise.

In [53]:
# Write your code here


**Q4.4** Print every 3rd element of a 1-20 array.

In [54]:
# Write your code here


## 5. Data Types & Coercion

_Mixed types auto-upcast to one common dtype | `.astype(type)` → explicit conversion_


**Q5.1** Create an array mixing ints and floats — check the resulting dtype.

In [55]:
# Write your code here


**Q5.2** Convert a float array [1.9, 2.5, 3.1] to integers using astype.

In [56]:
# Write your code here


## 6. Vectorized Arithmetic & Boolean Masking

_`a + b`, `a * b`, `a ** 2` → element-wise ops | `arr[arr > x]` → boolean filtering_


**Q6.1** Create two same-size arrays and compute their sum, product, and squares.

In [57]:
# Write your code here


**Q6.2** Create an array of 10 random-looking numbers of your choice, then filter out only values greater than 15 using a boolean mask.

In [58]:
# Write your code here


## 7. Random Module

_`np.random.seed(n)` → reproducibility | `.rand()` → uniform | `.randn()` → normal | `.randint(low,high,size)` → random ints | `.choice(arr,size)` → random sample | `.shuffle(arr)` → shuffle in place_


**Q7.1** Set a seed, generate a 3x3 uniform random array, and confirm reproducibility by rerunning with the same seed.

In [59]:
# Write your code here
np.random.seed(42)

arr1 = np.random.rand(3, 3)

np.random.seed(42)

arr2 = np.random.rand(3, 3)

print("First array:")
print(arr1)

print("\nSecond array:")
print(arr2)

print("\nSame:", np.array_equal(arr1, arr2))

First array:
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

Second array:
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

Same: True


**Q7.2** Generate 5 values from a normal distribution and 5 random integers between 1-100.

In [60]:
# Write your code here
normal_values = np.random.randn(5)
random_integers = np.random.randint(1, 101, 5)

print("Normal values:", normal_values)
print("Random integers:", random_integers)

Normal values: [-0.58087813 -0.52516981 -0.57138017 -0.92408284 -2.61254901]
Random integers: [49 91 59 42 92]


**Q7.3** Randomly pick 3 values (no repeats) from a list of 8 items, then shuffle a 1-10 array.

In [61]:
# Write your code here
items = np.array([10, 20, 30, 40, 50, 60, 70, 80])

selected = np.random.choice(items,3,replace=False)

arr = np.arange(1, 11)
np.random.shuffle(arr)

print("Selected:", selected)
print("Shuffled:", arr)

Selected: [10 20 50]
Shuffled: [ 6  4  2  7  1  8 10  5  3  9]


## 8. Reduction & Axis Rules

_`.sum()` / `.mean()` / `np.median()` → aggregations | `axis=0` → column-wise | `axis=1` → row-wise_


**Q8.1** Create a 3x3 matrix. Find the total sum, sum along axis=0, sum along axis=1.

In [62]:
# Write your code here
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Total:", arr.sum())
print("Axis 0:", arr.sum(axis=0))
print("Axis 1:", arr.sum(axis=1))

Total: 45
Axis 0: [12 15 18]
Axis 1: [ 6 15 24]


**Q8.2** Find the mean and median of the same matrix.

In [63]:
# Write your code here
print("Mean:", arr.mean())
print("Median:", np.median(arr))

Mean: 5.0
Median: 5.0


## 9. Broadcasting

_Shapes match if equal or one of them is 1 (compared right to left) | smaller array auto-expands to fit_


**Q9.1** Add a (3,3) ones matrix with a 1D array of length 3 — observe the broadcast.

In [64]:
# Write your code here
matrix = np.ones((3, 3))
vector = np.array([10, 20, 30])

result = matrix + vector

print(result)

[[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]


**Q9.2** Create a row vector (1,3) and column vector (3,1), add them, and check the resulting shape.

In [65]:
# Write your code here
row = np.array([[1, 2, 3]])
column = np.array([
    [10],
    [20],
    [30]
])

result = row + column

print(result)
print("Shape:", result.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
Shape: (3, 3)


## 10. Reshaping & Dimension Expansion

_`reshape(-1, n)` → auto-calculate the other dimension | `arr[np.newaxis, :]` → row vector | `arr[:, np.newaxis]` → column vector_


**Q10.1** Create a 12-element array and reshape it using -1 so it has 4 columns.

In [66]:
# Write your code here
arr = np.arange(12)

result = arr.reshape(-1, 4)

print(result)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Q10.2** Take a 3-element 1D array and convert it into a row vector and a column vector using np.newaxis.

In [67]:
# Write your code here
arr = np.array([1, 2, 3])

row = arr[np.newaxis, :]
column = arr[:, np.newaxis]

print("Row vector:")
print(row)

print("Column vector:")
print(column)

print("Row shape:", row.shape)
print("Column shape:", column.shape)

Row vector:
[[1 2 3]]
Column vector:
[[1]
 [2]
 [3]]
Row shape: (1, 3)
Column shape: (3, 1)


## 11. Flatten vs Ravel

_`.flatten()` → returns a copy (original safe) | `.ravel()` → returns a view (original can change too)_


**Q11.1** Create a 2D array, flatten it with both methods, modify the first element of each result, and check which one affects the original array.

In [68]:
# Write your code here
arr = np.array([
    [1, 2],
    [3, 4]
])

flat = arr.flatten()
ravel = arr.ravel()

flat[0] = 100
ravel[0] = 200

print("Original:")
print(arr)

print("Flatten:")
print(flat)

print("Ravel:")
print(ravel)

Original:
[[200   2]
 [  3   4]]
Flatten:
[100   2   3   4]
Ravel:
[200   2   3   4]


## 12. Stacking & Concatenation

_`np.vstack()` → stack rows | `np.hstack()` → stack columns | `np.concatenate(axis=)` → general version_


**Q12.1** Create two 2x2 arrays. Combine them using vstack, hstack, and concatenate on both axis=0 and axis=1.

In [69]:
# Write your code here
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

print("vstack:")
print(np.vstack((a, b)))

print("\nhstack:")
print(np.hstack((a, b)))

print("\nconcatenate axis=0:")
print(np.concatenate((a, b), axis=0))

print("\nconcatenate axis=1:")
print(np.concatenate((a, b), axis=1))

vstack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack:
[[1 2 5 6]
 [3 4 7 8]]

concatenate axis=0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

concatenate axis=1:
[[1 2 5 6]
 [3 4 7 8]]


## 13. np.where — Conditional Logic

_`np.where(cond, a, b)` → element-wise if/else | `np.where(cond)` → returns matching indices_


**Q13.1** Create a 6-element array. Label each value 'High' or 'Low' based on a threshold using np.where.

In [70]:
# Write your code here
arr = np.array([5, 12, 20, 8, 25, 15])

threshold = 15

result = np.where(arr > threshold, "High", "Low")

print(result)

['Low' 'Low' 'High' 'Low' 'High' 'Low']


**Q13.2** Use np.where (without true/false args) to find the indices of values above that threshold.

In [71]:
# Write your code here
indices = np.where(arr > threshold)

print(indices)

(array([2, 4]),)


## 14. Matrix Operations & Transpose

_`*` → element-wise multiply | `@` / `np.dot()` → matrix multiplication | `.T` → transpose (rows ↔ cols)_


**Q14.1** Create two 2x2 matrices. Compute their element-wise product and their matrix product (using both @ and np.dot).

In [72]:
# Write your code here
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

print("Element-wise product:")
print(a * b)

print("\nMatrix product using @:")
print(a @ b)

print("\nMatrix product using np.dot:")
print(np.dot(a, b))

Element-wise product:
[[ 5 12]
 [21 32]]

Matrix product using @:
[[19 22]
 [43 50]]

Matrix product using np.dot:
[[19 22]
 [43 50]]


**Q14.2** Print the transpose of the first matrix.

In [73]:
# Write your code here
print(a.T)

[[1 3]
 [2 4]]


---
## CRUD Operations on Arrays

_Create, Read, Update, Delete/Insert — arrays are fixed-size, so delete/insert return a new array rather than modifying in place._


## 15. CRUD — Create & Read

_Create = `np.array()`/creation helpers | Read = indexing & slicing_


**Q15.1** Create a 1D array of 8 integers and a 2D array of shape (3,3).

In [74]:
# Write your code here
arr1 = np.array([10, 20, 30, 40, 50, 60, 70, 80])

arr2 = np.arange(1, 10).reshape(3, 3)

print("1D array:")
print(arr1)

print("\n2D array:")
print(arr2)

1D array:
[10 20 30 40 50 60 70 80]

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Q15.2** Read the element at index 3 from the 1D array, and the middle row from the 2D array.

In [75]:
# Write your code here
print("Index 3:", arr1[3])
print("Middle row:", arr2[1])

Index 3: 40
Middle row: [4 5 6]


## 16. CRUD — Update

_`arr[i] = val` or `arr[slice] = val` → updates values directly (arrays are mutable)_


**Q16.1** Update index 2 of your 1D array to 100.

In [76]:
# Write your code here
arr1[2] = 100

print(arr1)

[ 10  20 100  40  50  60  70  80]


**Q16.2** Update the entire second row of your 2D array to [0, 0, 0].

In [77]:
# Write your code here
arr2[1] = [0, 0, 0]

print(arr2)

[[1 2 3]
 [0 0 0]
 [7 8 9]]


## 17. CRUD — Delete & Insert

_`np.delete(arr, idx, axis=)` → remove & return new array | `np.insert(arr, idx, val)` → insert value | `np.append(arr, val)` → add at the end_


**Q17.1** Delete the element at index 0 from your 1D array (store as a new variable).

In [78]:
# Write your code here
new_arr = np.delete(arr1, 0)

print(new_arr)

[ 20 100  40  50  60  70  80]


**Q17.2** Delete the last column from your 2D array.

In [79]:
# Write your code here
new_arr = np.delete(arr1, 0)

print(new_arr)

[ 20 100  40  50  60  70  80]


**Q17.3** Use np.append to add 99 to the end of your 1D array, and np.insert to insert 50 at index 1.

In [80]:
# Write your code here
appended = np.append(arr1, 99)
inserted = np.insert(arr1, 1, 50)

print("After append:")
print(appended)

print("\nAfter insert:")
print(inserted)

After append:
[ 10  20 100  40  50  60  70  80  99]

After insert:
[ 10  50  20 100  40  50  60  70  80]


## 18. Combined Practice

_No new functions — just combining what's covered above_


**Q18.1** Create a 5x5 array (1-25), extract its center 3x3 block, then find the row-wise sum of that block.

In [81]:
# Write your code here
arr = np.arange(1, 26).reshape(5, 5)

print("Original:")
print(arr)

center = arr[1:4, 1:4]

print("\nCenter 3x3:")
print(center)

row_sum = center.sum(axis=1)

print("\nRow-wise sum:")
print(row_sum)

Original:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Center 3x3:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Row-wise sum:
[24 39 54]


**Q18.2** Create two 1D int arrays, stack them with vstack, add 0.5 to the result and check the dtype coercion.

In [82]:
# Write your code here
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))

print("Before adding 0.5:")
print(result)
print("dtype:", result.dtype)

result = result + 0.5

print("\nAfter adding 0.5:")
print(result)
print("dtype:", result.dtype)

Before adding 0.5:
[[1 2 3]
 [4 5 6]]
dtype: int64

After adding 0.5:
[[1.5 2.5 3.5]
 [4.5 5.5 6.5]]
dtype: float64


**Q18.3** Create a 4x4 matrix with np.diag() using diagonal values 2,4,6,8, then find its transpose.

In [83]:
# Write your code here
arr = np.diag([2, 4, 6, 8])

print("Matrix:")
print(arr)

print("\nTranspose:")
print(arr.T)

Matrix:
[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]

Transpose:
[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]
