In [2]:
import numpy as np


In [4]:
# M = 3X4 matrix of ones add[10,20,30] so that each row gets a diffrent value(row 0 +10, row 1 +20, row 2 +30)
M = np.ones((3, 4))
add = np.array([10, 20, 30]).reshape(-1, 1)
M += add
print(M)

[[11. 11. 11. 11.]
 [21. 21. 21. 21.]
 [31. 31. 31. 31.]]


In [5]:
#table of 10 in one line using broadcasting
table = np.arange(1,11).reshape(-1,1) 
print(table * 10)

[[ 10]
 [ 20]
 [ 30]
 [ 40]
 [ 50]
 [ 60]
 [ 70]
 [ 80]
 [ 90]
 [100]]


In [ ]:
arr = np.arange(1,7).reshape(2,3)
print("Original array (arr):", arr)
f = arr.flatten()
r = arr.ravel()
f[0] = 100
r[0] = 500
print("Original array (arr):", arr)
print("Flattened array (f):", f)
print("Raveled array (r):", r) 



Original array (arr): [[1 2 3]
 [4 5 6]]
Original array (arr): [[500   2   3]
 [  4   5   6]]
Flattened array (f): [100   2   3   4   5   6]
Raveled array (r): [500   2   3   4   5   6]


for stacking we sue np.vstack() ==> top to bottom add
                    np.hstack() ==> side to side add

In [ ]:
#np.vstack() is used to stack arrays in sequence vertically (row wise). It takes a tuple of arrays as input and returns a single array that is the vertical concatenation of the input arrays. The input arrays must have the same number of columns.
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

arr3 = np.vstack((arr1,arr2)) # vertical stack
print("Vertical stack of arr1 and arr2:\n", arr3)

Vertical stack of arr1 and arr2:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
#np.hstack() is used to stack arrays in sequence horizontally (column wise). It takes a tuple of arrays as input and returns a single array that is the horizontal concatenation of the input arrays. The input arrays must have the same number of rows.
arr4 = np.hstack((arr1, arr2)) # horizontal stack
print("Horizontal stack of arr1 and arr2:\n", arr4)

Horizontal stack of arr1 and arr2:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [17]:
# np.concatenate() is used to join two or more arrays along an existing axis. It takes a tuple of arrays as input and returns a single array that is the concatenation of the input arrays. The input arrays must have the same shape, except in the dimension corresponding to the axis along which they are being concatenated.
# using axis=0, the arrays are concatenated vertically (row wise), while using axis=1, the arrays are concatenated horizontally (column wise).

print(arr3, arr4)
print("Concatenation of arr3 and arr4 along axis 0:\n", np.concatenate((arr1, arr2), axis=0))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Concatenation of arr3 and arr4 along axis 0:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
arr = np.array([2,-10,20,-15,-18,10])
arr1 = np.where(arr<0,0,arr)
print("Original array:", arr)
print("Modified array:", arr1)

arr2 = np.array([20,40,55,75,80,35])
arr3 = np.where(arr2<40, "Fail", "Pass")
print(arr3)

arr4 = np.where(arr2>80, "A",
                 np.where((79>arr2) & (arr2>60), "B", "Fail"))
print(arr4)

marks = np.array([92, 61, 45, 78, 33, 55])
grades= np.where(marks>=75,"A",
         np.where(marks>=50,"B","Fail"))

print(grades)

Original array: [  2 -10  20 -15 -18  10]
Modified array: [ 2  0 20  0  0 10]
['Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail']
['Fail' 'Fail' 'Fail' 'B' 'Fail' 'Fail']
['A' 'B' 'Fail' 'A' 'Fail' 'B']


In [ ]:
#print the indices of the elements in the array that are greater than 60

marks = np.array([92, 61, 45, 78, 33, 55])
idx = np.where(marks>60)[0]
print(idx)

[0 1 3]


In [ ]:
# a * b --> multiply each element position wise and return a new array with the result.
#  If the shapes of the two arrays are not the same, numpy will try to broadcast them to a common shape before performing the operation. 
# Broadcasting is a set of rules that numpy follows to perform operations on arrays of different shapes. 
# It allows numpy to perform element-wise operations on arrays of different shapes without explicitly reshaping them.




# np.dot() is a function in numpy that computes the dot product of two arrays. 
# The dot product is a mathematical operation that takes two equal-length sequences of numbers (usually vectors) and returns a single number. 
# In numpy, the dot() function can be used to compute the dot product of two 1-D arrays, or to perform matrix multiplication on 2-D arrays.

# a @ b --> dot product of two arrays. It is equivalent to np.dot(a,b) and can be used for both 1-D and 2-D arrays.



# x.T --> transpose the array 

In [71]:

s1 = [72, 85, 60, 91]
s2 = [45, 30, 98, 55]
s3 = [88, 66, 74, 100]
old = np.array([['62', '71', '55', '80'],
                ['49', '58', '66', '73']])

#1.
arr = np.array([s1, s2, s3])
print("Original array:\n", arr)

#2.
# students= np.where(arr[0:, :1])[0]
print("Students:\n", arr.shape[0])

# subject = np.where(arr[:, :4])[0]
print("Subjects:\n", arr.shape[1])


#3
print("total elements:\n",np.size(arr))

#4
print("decimal values:\n",arr.astype(float))

#5
old = old.astype('int32')
print("Sum of old array along axis 1:\n", np.sum(old, axis=1)) 

#6
# print(arr.astype('int32'))
# print(np.vstack((table, np.sum(table, axis=1).reshape(-1, 1))))

Original array:
 [[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]]
Students:
 3
Subjects:
 4
total elements:
 12
decimal values:
 [[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]]
Sum of old array along axis 1:
 [268 246]


In [70]:
#1
table = np.zeros((6,4))
print("Table:\n", table)

#2
table2 = np.full((6,4), 35)
print("Table2:\n", table2)

#3
roll_No = np.arange(101, 131, 2)
print("Roll Numbers:\n", roll_No)

#4
print("7 equally spaced time markers:\n",np.linspace(0,3,7))

#5
arr = np.eye(5, dtype=int) * 10
print("diagonal array:\n", arr)

#6
arr1 = np.full((4,4), 35, dtype=int) + np.eye(4, dtype=int) * 65
print("Array1:\n", arr1)

Table:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Table2:
 [[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]
Roll Numbers:
 [101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
7 equally spaced time markers:
 [0.  0.5 1.  1.5 2.  2.5 3. ]
diagonal array:
 [[10  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 10]]
Array1:
 [[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]
